module.exports = {
  bios: [
    '*Insert your bio here*',
    'A Caffeine dependent life-form',
    'A human. Being.',
    'A man of mystery and power, whose power is exceeded only by his mystery',
    'Aggressively infancy and stuff',
    'All you hipsters need to stop wearing Nirvana shirts if you don’t even listen to them.',
    'Analogue at birth, digital by design',
    'Are you a banker because I’d like you to leave me a loan',
    'Bald. Often Unreliable. Easily distracted',
    'Born at a very young age',
    'Buddy, can you paradigm?',
    'Camping is intents',
    'Chocolate doesn’t ask questions, chocolate understands',
    'Coffee-Drinker, eReader Addict, Blogger. I’m very busy and awesome',
    'Currently starring in my own reality show titled, A Modern Cinderella; One Girl’s Search for Love and Shoe',
    'Currently working towards an MBA with an emphasis in fantasy football',
    'Don’t think for a second that I actually care what you have to say',
    'Eating a whole apple core because you can’t be bothered going to the bin, admit it, you’ve done it.',
    'Every storm runs out of rain',
    'Fabulous ends in “us” coincidence? I think not',
    'Generally, the path of least resistance appeals. Also, I am excellent at parallel parking.',
    'God bless this hot mess',
    'Good Samaritan, washed-up athlete, especially gifted napper.',
    'Have lots of hair and like ugly things',
    'Here to serve…. the cat overlord',
    'I absolutely hate Instagram, and anything else having to do with hashtags.',
    'I always feel sad for seedless watermelons, because what if they wanted babies?',
    'I am coming back to face the reality that a normal day is not beer on the beach or calamari in the belly.',
    'I can quote (Insert movie) better than you and all your friends.',
    'I Can’t remember who I stole my bio from or why',
    'I have not lost my mind – it’s backed up on HD somewhere.',
    'I have this new theory that human adolescence doesn’t end until your early thirties.',
    'I hope one day I love something the way women in commercials love yogurt',
    'I looked at my Instagram photos and realized I look beautiful.',
    'I prefer my puns intended',
    'I put the hot in psychotic',
    'I recently gave up Warcraft so my productivity, and drinking, have increased dramatically.',
    'I shouldn’t be allowed to go on Snapchat, Facebook or Instagram when I’m drunk!',
    'I talk like a baby and I never pay for drinks.',
    'I used to act. I also belly dance and eat Jolly Ranchers – not always at the same time though.',
    'I was addicted to hokey pokey but I turned myself around',
    'I will go into survival mode if tickled',
    'I’m a force to be reckoned with, I reckon',
    'I’m not glad it’s “Friday” I’m glad it’s “Today”. Love your life 7 days a week.',
    'I’m a Texan with lots of opinions and pretty hair.',
    'I’m actually not funny. I’m just really mean and people think I am joking.',
    'I’m here to avoid friends on Facebook.',
    'I’m not smart. I just wear glasses.',
    'I’m not sure how many problems I have because math is one of them',
    'I’m real and I hope some of my followers are too.',
    'I’m really a giant cupcake. Afraid of roller coasters and dry ice',
    'If I could sum up my life in one line I would die of embarrassment',
    'If you don’t have anything nice to say, come sit by me, and we can make fun of people together',
    'In search of sleep, sanity, & The Shire',
    'Insert pretentious stuff about myself here.',
    'Just another paper cut survivor',
    'Just keep swimming',
    'Life is dumb and I want to sleep',
    'Living vicariously through myself',
    'Making the Snuggie look good since 2009.',
    'Mama said life is like a box of chocolates, you never know what your gonna get',
    'Mermaids don’t do homework',
    'My hobbies are breakfast, lunch, and dinner.',
    'My life is about as organized as the $5 DVD bin at Wal-Mart',
    'My life was changed by a train.',
    'Promo Codes for life.',
    'My relationship status? Netflix, Oreos and sweatpants',
    'Naturally and artificially flavored',
    'Nice guys finish lunch.',
    'Nothing more than a man who cared enough to try',
    'Oh I’m sorry was my sass too much for you?',
    'OMG no one cares',
    'Only Swag girls are fascinated by hashtags on the Facebook.',
    'Perfect has 7 letters and so does meeeeee. Coincidence? I think not.',
    'Please insert pretentious crap about myself here.',
    'Pour yourself a drink, put on some lipstick, and pull yourself together.',
    'Putting’ the ‘elation’ in ‘Public Relations’',
    'Recommended by 4 out of 5 people that recommend things.',
    'Recovering ice cream addict',
    'Someday, there’s going to be an updated version of me.',
    'Sometimes I just want to give it all up and become a handsome billionaire.',
    'Spreading smiles like they’re herpes',
    'Stay classy',
    'Super cali swagilistic hella dopeness',
    'That awkward moment you get accepted to all the schools you applied for.',
    'The fat on my body is designer',
    'The only thing stopping me from being pure white trash is my lack of motivation.',
    'There shouldn’t be a fear of getting old. It’s the fear of not getting there that scares me.',
    'There’s no such thing as darkness, just an absence of light',
    'To infinity and beyond',
    'Trying to elevate small talk to medium talk.',
    'Where the hell am I, and how did I get here?',
    'White lips, pale face, I hate the entire human race',
    'Why look up at the stars when the biggest star is me',
    'Winner of World’s Best Wife Award (Category: Nagging)',
    'Words cannot express my love & passion for Fridays!',
    'You can’t fix stupid, no matter how much duct tape you use over their mouth!',
    'You is kind, you is smart, you is important',
    'You know your in love when you can’t fall asleep because reality is finally better than your dreams.',
    'You’re too rad to be sad.',
    'You’re a 10, on the pH scale, maybe. Cuz you’re basic ',
    'Millennial and proud of it',
    'Things just ain’t the same for gangstas',
    'Car, house, or trip to Thailand? Let’s pack our bags',
    'The reason I like you is simple, love, laughter, and your smile',
    'How we live our life is far more important than how we say we live our life',
    'The best of me is yet to come',
    'Making history',
    'On a scale of 1 to 10, I’m a 15',
    'Math: Mental Abuse To Humans',
    'Let go and let the world pass through your fingertips',
    'Is it bad I’m constantly craving either cupcakes or donuts?'
  ]
}